server:
  port: 8080
spring:
  datasource:
    driver-cLass-name: com.mysql.jdbc.Driver
    password: Helina2001
    urL: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sqL: 'true'
welcome:
  message: Welcome to Daily Code Buffer, YAML
